### ISSUE TITLE
The Github version has stopped working from Annotate Peak

### ISSUE THREAD

**Issue by DrSoftouch** [showteeth/DEbPeak#3]
I even ran this directly on the package RNA and ATAC seq files after installation.

It was working just 2 weeks ago, and now suddenly it has stopped. I checked if you made update, but it doesn't look like it.

Can you clarify what is wrong?

**Comment by DrSoftouch** [comment]
It started working again just after I opened issue. Quite strange.

**Comment by showteeth** [comment]
Hi,
I didn’t make any updates recently.
Have you installed any packages recently? And can you send me the codes you
used and the error message you got?

Sincerely,
YB

DrSoftouch ***@***.***>于2023年2月1日 周三14:13写道：
